apiVersion: v1
kind: Namespace
metadata:
  name: sai
  labels:
    app.kubernetes.io/managed-by: argocd
    name: sai
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    description: "Namespace for the sai-related resources"
